insert into public.rag_documents (
  id,
  destination_slug,
  destination_name,
  language,
  content_type,
  title,
  body,
  tags,
  metadata,
  source,
  source_url,
  source_confidence,
  content_version
)
values
(
  'beijing:positioning_overview:beijing-positioning-overview',
  'beijing',
  'Beijing',
  'en',
  'positioning_overview',
  'Beijing positioning overview',
  'China''s capital is strongest when it is read as a city of order, ritual, power, and ordinary courtyard life.

Why visit: Beijing gives foreign travelers a clear way to understand how imperial authority, ceremonial space, socialist memory, and neighborhood texture coexist. The value is not only the Forbidden City or the Great Wall. It is the contrast between monumental axes and human-scale hutongs, between state ritual and small daily habits.

Avoid framing: Do not frame Beijing as a checklist of famous sights. The premium version is about reading power, space, ritual, and neighborhood life with context.',
  array['why_visit', 'positioning', 'avoid_generic']::text[],
  '{"best_for":["First-time visitors who want historical context","Architecture and urban planning travelers","Culture-led families or private small groups","Museum, history, and diplomacy-minded guests"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:sell_point:imperial-order-and-the-central-axis',
  'beijing',
  'Beijing',
  'en',
  'sell_point',
  'Imperial order and the Central Axis',
  'Beijing selling point: Imperial order and the Central Axis. Use palace space, gates, altars, and axial planning to explain how power was staged, not just where emperors lived.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:sell_point:hutongs-and-courtyard-life',
  'beijing',
  'Beijing',
  'en',
  'sell_point',
  'Hutongs and courtyard life',
  'Beijing selling point: Hutongs and courtyard life. Slow walks, local markets, and courtyard conversations make the capital feel lived-in rather than only monumental.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:sell_point:a-strong-first-china-orientation',
  'beijing',
  'Beijing',
  'en',
  'sell_point',
  'A strong first-China orientation',
  'Beijing selling point: A strong first-China orientation. Beijing works well as the first city for travelers who need historical grammar before moving into craft, tea, or regional culture.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":3}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:audience_fit:beijing-best-fit-travelers',
  'beijing',
  'Beijing',
  'en',
  'audience_fit',
  'Beijing best-fit travelers',
  'Beijing is best for: First-time visitors who want historical context; Architecture and urban planning travelers; Culture-led families or private small groups; Museum, history, and diplomacy-minded guests.',
  array['audience', 'conversion']::text[],
  '{"best_for":["First-time visitors who want historical context","Architecture and urban planning travelers","Culture-led families or private small groups","Museum, history, and diplomacy-minded guests"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:route_seed:capital-order',
  'beijing',
  'Beijing',
  'en',
  'route_seed',
  'Capital Order',
  'Capital Order (3 days): Central Axis, Forbidden City context, altar culture, hutong walks, and one carefully paced Great Wall day.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":1,"duration":"3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:route_seed:courtyard-beijing',
  'beijing',
  'Beijing',
  'en',
  'route_seed',
  'Courtyard Beijing',
  'Courtyard Beijing (4 days): Hutongs, courtyard meals, local markets, temple routes, and slower neighborhood interpretation.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":2,"duration":"4 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:route_seed:beijing-as-prologue',
  'beijing',
  'Beijing',
  'en',
  'route_seed',
  'Beijing as Prologue',
  'Beijing as Prologue (2-3 days): Use Beijing to establish China''s historical frame before continuing to Jingdezhen, Quanzhou, Wudang, or Chengdu.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":3,"duration":"2-3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:traveler_faq:why-should-a-culture-focused-traveler-start-in-beijing',
  'beijing',
  'Beijing',
  'en',
  'traveler_faq',
  'Why should a culture-focused traveler start in Beijing?',
  'Question: Why should a culture-focused traveler start in Beijing?
Answer direction: It gives the clearest opening frame for Chinese history, space, hierarchy, ritual, and urban continuity.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:traveler_faq:how-do-we-avoid-making-beijing-feel-generic',
  'beijing',
  'Beijing',
  'en',
  'traveler_faq',
  'How do we avoid making Beijing feel generic?',
  'Question: How do we avoid making Beijing feel generic?
Answer direction: Reduce checklist pressure and build the route around contrasts: axis and alley, palace and courtyard, ceremony and daily life.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:positioning_overview:chengdu-positioning-overview',
  'chengdu',
  'Chengdu',
  'en',
  'positioning_overview',
  'Chengdu positioning overview',
  'Chengdu is the easiest major Chinese city for foreigners to love through food, pandas, tea houses, and an unhurried social rhythm.

Why visit: Chengdu should lead with Sichuan food and pandas because those are the strongest emotional entry points for most foreign visitors. The deeper sell is that food, tea, parks, conversation, and neighborhood ease reveal a relaxed but culturally dense version of urban China.

Avoid framing: Do not reduce Chengdu to spicy food alone. Food and pandas should open the door, but the premium story is local ease, tea-house rhythm, and Sichuan social life.',
  array['why_visit', 'positioning', 'avoid_generic']::text[],
  '{"best_for":["Food-first travelers","Families and couples","Travelers who want China to feel relaxed, not overwhelming","Guests pairing pandas with Sichuan culture"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:sell_point:sichuan-food-as-culture',
  'chengdu',
  'Chengdu',
  'en',
  'sell_point',
  'Sichuan food as culture',
  'Chengdu selling point: Sichuan food as culture. Hotpot, snacks, market flavor, peppercorn aroma, and local dining habits turn meals into the main cultural route.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:sell_point:pandas-as-emotional-gateway',
  'chengdu',
  'Chengdu',
  'en',
  'sell_point',
  'Pandas as emotional gateway',
  'Chengdu selling point: Pandas as emotional gateway. Pandas create immediate desire, especially for families and first-time visitors, then the trip can deepen into local life.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:sell_point:tea-house-pace',
  'chengdu',
  'Chengdu',
  'en',
  'sell_point',
  'Tea-house pace',
  'Chengdu selling point: Tea-house pace. Parks, tea houses, mahjong, and long afternoons make Chengdu feel approachable, social, and human.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":3}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:audience_fit:chengdu-best-fit-travelers',
  'chengdu',
  'Chengdu',
  'en',
  'audience_fit',
  'Chengdu best-fit travelers',
  'Chengdu is best for: Food-first travelers; Families and couples; Travelers who want China to feel relaxed, not overwhelming; Guests pairing pandas with Sichuan culture.',
  array['audience', 'conversion']::text[],
  '{"best_for":["Food-first travelers","Families and couples","Travelers who want China to feel relaxed, not overwhelming","Guests pairing pandas with Sichuan culture"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:route_seed:food-and-panda-first',
  'chengdu',
  'Chengdu',
  'en',
  'route_seed',
  'Food and Panda First',
  'Food and Panda First (3 days): Panda base early morning, neighborhood snacks, hotpot, tea house, and a market-led flavor walk.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":1,"duration":"3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:route_seed:slow-chengdu',
  'chengdu',
  'Chengdu',
  'en',
  'route_seed',
  'Slow Chengdu',
  'Slow Chengdu (4 days): Parks, teahouses, old streets, Sichuan opera, food neighborhoods, and one gentle countryside or craft extension.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":2,"duration":"4 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:route_seed:chengdu-and-chongqing-contrast',
  'chengdu',
  'Chengdu',
  'en',
  'route_seed',
  'Chengdu and Chongqing Contrast',
  'Chengdu and Chongqing Contrast (5-6 days): Pair Chengdu''s softness and food culture with Chongqing''s 8D visual intensity and river-city drama.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":3,"duration":"5-6 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:traveler_faq:is-chengdu-only-about-pandas',
  'chengdu',
  'Chengdu',
  'en',
  'traveler_faq',
  'Is Chengdu only about pandas?',
  'Question: Is Chengdu only about pandas?
Answer direction: No. Pandas are the strongest hook, but the memorable trip comes from food, tea houses, parks, and local social rhythm.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:traveler_faq:who-is-chengdu-best-for',
  'chengdu',
  'Chengdu',
  'en',
  'traveler_faq',
  'Who is Chengdu best for?',
  'Question: Who is Chengdu best for?
Answer direction: Travelers who want culture through appetite, comfort, and daily life rather than only monuments.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:positioning_overview:chongqing-positioning-overview',
  'chongqing',
  'Chongqing',
  'en',
  'positioning_overview',
  'Chongqing positioning overview',
  'Chongqing is China''s most cinematic 8D mountain city: cyberpunk-feeling nights, impossible levels, hotpot heat, rivers, bridges, and vertical daily life.

Why visit: Chongqing should be sold as a sensory urban experience that feels unlike flat-grid cities. Foreign travelers remember the way trains, bridges, stairs, riverbanks, cliffside buildings, neon, fog, and hotpot combine into a city that feels almost fictional but is fully lived-in.

Avoid framing: Do not present Chongqing as just another food city or a list of viral photo spots. The sell is the lived 8D geography plus night movement, appetite, and river-city scale.',
  array['why_visit', 'positioning', 'avoid_generic']::text[],
  '{"best_for":["Visual travelers and photographers","Young premium travelers who want atmosphere","Food and nightlife-led guests","Visitors who want a city that feels different from Beijing or Shanghai"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:sell_point:cyberpunk-feeling-8d-geography',
  'chongqing',
  'Chongqing',
  'en',
  'sell_point',
  'Cyberpunk-feeling 8D geography',
  'Chongqing selling point: Cyberpunk-feeling 8D geography. Layered roads, monorails, cliffside buildings, river crossings, and sudden elevation changes create the city''s strongest visual identity.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:sell_point:night-city-and-river-drama',
  'chongqing',
  'Chongqing',
  'en',
  'sell_point',
  'Night city and river drama',
  'Chongqing selling point: Night city and river drama. Neon, humidity, bridges, ferries, and high viewpoints make Chongqing especially strong for evening routes and photography.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:sell_point:hotpot-and-mountain-city-appetite',
  'chongqing',
  'Chongqing',
  'en',
  'sell_point',
  'Hotpot and mountain-city appetite',
  'Chongqing selling point: Hotpot and mountain-city appetite. Food is not decoration here. Heat, noise, late meals, and communal dining match the city''s physical intensity.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":3}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:audience_fit:chongqing-best-fit-travelers',
  'chongqing',
  'Chongqing',
  'en',
  'audience_fit',
  'Chongqing best-fit travelers',
  'Chongqing is best for: Visual travelers and photographers; Young premium travelers who want atmosphere; Food and nightlife-led guests; Visitors who want a city that feels different from Beijing or Shanghai.',
  array['audience', 'conversion']::text[],
  '{"best_for":["Visual travelers and photographers","Young premium travelers who want atmosphere","Food and nightlife-led guests","Visitors who want a city that feels different from Beijing or Shanghai"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:route_seed:8d-city-immersion',
  'chongqing',
  'Chongqing',
  'en',
  'route_seed',
  '8D City Immersion',
  '8D City Immersion (2-3 days): Layered transit, old stairs, river crossings, high viewpoints, neon night walks, and one proper hotpot evening.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":1,"duration":"2-3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:route_seed:cyberpunk-chongqing',
  'chongqing',
  'Chongqing',
  'en',
  'route_seed',
  'Cyberpunk Chongqing',
  'Cyberpunk Chongqing (3 days): Focus on visual rhythm: monorail moments, bridges, elevated streets, fog, nightscape, and dense local neighborhoods.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":2,"duration":"3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:route_seed:sichuan-basin-pairing',
  'chongqing',
  'Chongqing',
  'en',
  'route_seed',
  'Sichuan Basin Pairing',
  'Sichuan Basin Pairing (5-6 days): Contrast Chengdu''s ease and pandas with Chongqing''s vertical drama, hotpot, and urban intensity.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":3,"duration":"5-6 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:traveler_faq:why-is-chongqing-called-an-8d-city',
  'chongqing',
  'Chongqing',
  'en',
  'traveler_faq',
  'Why is Chongqing called an 8D city?',
  'Question: Why is Chongqing called an 8D city?
Answer direction: Because roads, rails, buildings, riverbanks, and walkways stack across multiple levels, making navigation feel vertical and cinematic.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:traveler_faq:is-chongqing-suitable-for-luxury-cultural-travel',
  'chongqing',
  'Chongqing',
  'en',
  'traveler_faq',
  'Is Chongqing suitable for luxury cultural travel?',
  'Question: Is Chongqing suitable for luxury cultural travel?
Answer direction: Yes, if the route is curated around atmosphere, viewpoints, local food, and urban interpretation rather than generic viral stops.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:positioning_overview:quanzhou-positioning-overview',
  'quanzhou',
  'Quanzhou',
  'en',
  'positioning_overview',
  'Quanzhou positioning overview',
  'Quanzhou is a world-class Maritime Silk Road port where UNESCO heritage, plural religions, Hokkien memory, food, and craft still overlap in the streets.

Why visit: Quanzhou is strongest for travelers who want China connected to the wider world. Its value is not beach tourism. It is the rare combination of Song-Yuan maritime trade, temples, mosques, ancestral memory, overseas Chinese ties, foodways, and living craft traditions.

Avoid framing: Do not sell Quanzhou as a generic coastal city. The premium story is port memory, religious plurality, Hokkien identity, food, and hand-made heritage.',
  array['why_visit', 'positioning', 'avoid_generic']::text[],
  '{"best_for":["Southeast Asian Hokkien and diaspora travelers","UNESCO and maritime history travelers","Religion, food, and old-city walkers","Travelers seeking depth beyond famous first-tier cities"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:sell_point:maritime-silk-road-and-unesco-heritage',
  'quanzhou',
  'Quanzhou',
  'en',
  'sell_point',
  'Maritime Silk Road and UNESCO heritage',
  'Quanzhou selling point: Maritime Silk Road and UNESCO heritage. Quanzhou explains China as a global port civilization, not an isolated inland empire.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:sell_point:plural-religions-and-coexistence',
  'quanzhou',
  'Quanzhou',
  'en',
  'sell_point',
  'Plural religions and coexistence',
  'Quanzhou selling point: Plural religions and coexistence. Mosques, temples, shrines, churches, and trade memory give the city unusual interpretive depth for foreign visitors.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:sell_point:hokkien-diaspora-and-living-food-culture',
  'quanzhou',
  'Quanzhou',
  'en',
  'sell_point',
  'Hokkien diaspora and living food culture',
  'Quanzhou selling point: Hokkien diaspora and living food culture. For Southeast Asian travelers especially, Quanzhou can feel like an origin story for family memory, language, worship, and flavor.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":3}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:audience_fit:quanzhou-best-fit-travelers',
  'quanzhou',
  'Quanzhou',
  'en',
  'audience_fit',
  'Quanzhou best-fit travelers',
  'Quanzhou is best for: Southeast Asian Hokkien and diaspora travelers; UNESCO and maritime history travelers; Religion, food, and old-city walkers; Travelers seeking depth beyond famous first-tier cities.',
  array['audience', 'conversion']::text[],
  '{"best_for":["Southeast Asian Hokkien and diaspora travelers","UNESCO and maritime history travelers","Religion, food, and old-city walkers","Travelers seeking depth beyond famous first-tier cities"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:route_seed:maritime-world-city',
  'quanzhou',
  'Quanzhou',
  'en',
  'route_seed',
  'Maritime World City',
  'Maritime World City (3 days): Old port memory, UNESCO components, religious sites, street food, and a slow old-city route.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":1,"duration":"3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:route_seed:hokkien-roots',
  'quanzhou',
  'Quanzhou',
  'en',
  'route_seed',
  'Hokkien Roots',
  'Hokkien Roots (4 days): Ancestral halls, temple culture, food memory, diaspora interpretation, and optional clan or village extensions.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":2,"duration":"4 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:route_seed:craft-and-ritual-quanzhou',
  'quanzhou',
  'Quanzhou',
  'en',
  'route_seed',
  'Craft and Ritual Quanzhou',
  'Craft and Ritual Quanzhou (5 days): Zanhua, Nanyin, incense, tea, ceramics, local markets, and religious landscapes shaped into an immersive route.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":3,"duration":"5 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:traveler_faq:which-foreign-markets-are-most-naturally-attracted-to-quanzhou',
  'quanzhou',
  'Quanzhou',
  'en',
  'traveler_faq',
  'Which foreign markets are most naturally attracted to Quanzhou?',
  'Question: Which foreign markets are most naturally attracted to Quanzhou?
Answer direction: Philippines, Malaysia, Singapore, Indonesia, and Thailand are especially strong because of Hokkien, diaspora, food, and temple connections.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:traveler_faq:what-makes-quanzhou-different-from-xiamen',
  'quanzhou',
  'Quanzhou',
  'en',
  'traveler_faq',
  'What makes Quanzhou different from Xiamen?',
  'Question: What makes Quanzhou different from Xiamen?
Answer direction: Xiamen is easier and more polished; Quanzhou is deeper for maritime heritage, religious plurality, old streets, and living traditions.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:positioning_overview:jingdezhen-positioning-overview',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'positioning_overview',
  'Jingdezhen positioning overview',
  'Jingdezhen is not only a porcelain museum city; it is a living craft ecosystem where clay, kiln, glaze, studio, and global design still meet.

Why visit: Jingdezhen gives foreign travelers a tactile way into Chinese culture. Instead of only viewing heritage, they can understand material, process, labor, failure, beauty, and global trade through porcelain. It is especially strong for design-minded and craft-minded guests.

Avoid framing: Do not frame Jingdezhen as a shopping stop. The premium value is the craft ecosystem: kilns, studios, makers, materials, and global porcelain history.',
  array['why_visit', 'positioning', 'avoid_generic']::text[],
  '{"best_for":["Design, craft, and architecture travelers","Museum and collector audiences","Artists, students, and creative professionals","Travelers who prefer process over sightseeing"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:sell_point:world-porcelain-capital',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'sell_point',
  'World porcelain capital',
  'Jingdezhen selling point: World porcelain capital. The city''s global significance is easy to explain: porcelain from here shaped taste, trade, collecting, and design across continents.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:sell_point:living-studios-and-kilns',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'sell_point',
  'Living studios and kilns',
  'Jingdezhen selling point: Living studios and kilns. The best route should include makers, workshops, firing culture, and contemporary craft, not only museums.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:sell_point:high-value-craft-experience',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'sell_point',
  'High-value craft experience',
  'Jingdezhen selling point: High-value craft experience. Jingdezhen is ideal for travelers who want to learn by seeing hands, tools, material choices, and process.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":3}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:audience_fit:jingdezhen-best-fit-travelers',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'audience_fit',
  'Jingdezhen best-fit travelers',
  'Jingdezhen is best for: Design, craft, and architecture travelers; Museum and collector audiences; Artists, students, and creative professionals; Travelers who prefer process over sightseeing.',
  array['audience', 'conversion']::text[],
  '{"best_for":["Design, craft, and architecture travelers","Museum and collector audiences","Artists, students, and creative professionals","Travelers who prefer process over sightseeing"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:route_seed:porcelain-deep-dive',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'route_seed',
  'Porcelain Deep Dive',
  'Porcelain Deep Dive (3 days): Historic kilns, museum context, studio visits, market texture, and one hands-on making or glazing session.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":1,"duration":"3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:route_seed:designer-jingdezhen',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'route_seed',
  'Designer Jingdezhen',
  'Designer Jingdezhen (4 days): Contemporary studios, independent makers, material research, old kiln districts, and curated collecting guidance.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":2,"duration":"4 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:route_seed:porcelain-and-capital-contrast',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'route_seed',
  'Porcelain and Capital Contrast',
  'Porcelain and Capital Contrast (6-7 days): Pair Beijing''s imperial order with Jingdezhen''s material culture to show power, taste, trade, and craft.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":3,"duration":"6-7 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:traveler_faq:why-would-a-foreign-traveler-go-to-jingdezhen',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'traveler_faq',
  'Why would a foreign traveler go to Jingdezhen?',
  'Question: Why would a foreign traveler go to Jingdezhen?
Answer direction: Because it turns Chinese culture into something physical and understandable through clay, firing, craft, and global porcelain history.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:traveler_faq:is-jingdezhen-only-for-collectors',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'traveler_faq',
  'Is Jingdezhen only for collectors?',
  'Question: Is Jingdezhen only for collectors?
Answer direction: No. It is also strong for designers, families, students, artists, and travelers who want hands-on cultural experience.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:positioning_overview:jingmai-mountain-positioning-overview',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'positioning_overview',
  'Jingmai Mountain positioning overview',
  'Jingmai is a slow tea mountain world where ancient tea forests, villages, ecology, and ritual create a quieter, more contemplative China route.

Why visit: Jingmai should be developed as a high-aesthetic slow travel destination, not a conventional attraction cluster. Its power comes from tea landscapes, mountain air, village continuity, ethnic culture, ecology, and the emotional shift that happens when the trip slows down.

Avoid framing: Do not sell Jingmai as a fast sightseeing stop. The value depends on slowness, weather, tea ritual, mountain texture, and local interpretation.',
  array['why_visit', 'positioning', 'avoid_generic']::text[],
  '{"best_for":["Tea travelers and nature-focused guests","Slow travel and retreat-style visitors","Photographers and high-aesthetic travelers","Repeat China visitors seeking less obvious routes"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:sell_point:ancient-tea-forest-landscape',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'sell_point',
  'Ancient tea forest landscape',
  'Jingmai Mountain selling point: Ancient tea forest landscape. Tea is not just a drink here. It is a landscape, livelihood, ritual, ecology, and way to read time.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:sell_point:slow-mountain-travel',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'sell_point',
  'Slow mountain travel',
  'Jingmai Mountain selling point: Slow mountain travel. The appeal is pace reduction: mist, mornings, tea, walking, village stays, and distance from mass tourism.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:sell_point:a-strong-premium-retreat-angle',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'sell_point',
  'A strong premium retreat angle',
  'Jingmai Mountain selling point: A strong premium retreat angle. Jingmai fits travelers seeking silence, beauty, wellness-adjacent culture, and reflective travel without making it generic wellness tourism.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":3}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:audience_fit:jingmai-mountain-best-fit-travelers',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'audience_fit',
  'Jingmai Mountain best-fit travelers',
  'Jingmai Mountain is best for: Tea travelers and nature-focused guests; Slow travel and retreat-style visitors; Photographers and high-aesthetic travelers; Repeat China visitors seeking less obvious routes.',
  array['audience', 'conversion']::text[],
  '{"best_for":["Tea travelers and nature-focused guests","Slow travel and retreat-style visitors","Photographers and high-aesthetic travelers","Repeat China visitors seeking less obvious routes"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:route_seed:tea-forest-stay',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'route_seed',
  'Tea Forest Stay',
  'Tea Forest Stay (3 days): Village base, tea forest walks, tea tasting, mountain mornings, and conversations around ecology and craft.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":1,"duration":"3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:route_seed:slow-yunnan-tea-route',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'route_seed',
  'Slow Yunnan Tea Route',
  'Slow Yunnan Tea Route (5 days): Jingmai with nearby tea landscapes, village rhythm, light hiking, and careful lodge pacing.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":2,"duration":"5 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:route_seed:tea-and-craft-china',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'route_seed',
  'Tea and Craft China',
  'Tea and Craft China (7 days): Pair Jingmai''s tea ecology with Jingdezhen''s porcelain process for a material culture route.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":3,"duration":"7 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:traveler_faq:why-is-jingmai-worth-including',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'traveler_faq',
  'Why is Jingmai worth including?',
  'Question: Why is Jingmai worth including?
Answer direction: It adds quiet, ecology, tea culture, and emotional contrast to an itinerary that might otherwise be too city-heavy.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:traveler_faq:who-should-not-choose-jingmai',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'traveler_faq',
  'Who should not choose Jingmai?',
  'Question: Who should not choose Jingmai?
Answer direction: Travelers who want fast logistics, dense nightlife, or a simple checklist route may find it too slow.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:positioning_overview:wudang-mountain-positioning-overview',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'positioning_overview',
  'Wudang Mountain positioning overview',
  'Wudang Mountain is a Taoist sacred landscape where architecture, mountain paths, Taiji, breath, and internal practice give the trip spiritual weight.

Why visit: Wudang should be positioned around Taoist culture and Taiji, not just mountain scenery. For foreign travelers, it offers an unusually coherent combination of sacred architecture, philosophy, martial tradition, body practice, early light, and reflective travel.

Avoid framing: Do not sell Wudang as generic scenery or kung fu performance. The premium route needs Taoist context, Taiji literacy, mountain pacing, and quiet.',
  array['why_visit', 'positioning', 'avoid_generic']::text[],
  '{"best_for":["Taoism, philosophy, and martial culture travelers","Guests seeking reflective mountain travel","Wellness-adjacent travelers who want real culture","Repeat China visitors looking beyond standard routes"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:sell_point:taoist-sacred-mountain',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'sell_point',
  'Taoist sacred mountain',
  'Wudang Mountain selling point: Taoist sacred mountain. Temples, palaces, paths, and mountain orientation create a strong philosophical landscape, not just a scenic one.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:sell_point:taiji-and-internal-practice',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'sell_point',
  'Taiji and internal practice',
  'Wudang Mountain selling point: Taiji and internal practice. Short, well-contextualized practice sessions can make the destination memorable without pretending to be a training camp.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:sell_point:architecture-and-atmosphere',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'sell_point',
  'Architecture and atmosphere',
  'Wudang Mountain selling point: Architecture and atmosphere. Wudang''s appeal is strongest in early light, temple routes, clouds, silence, and the feeling of movement through a sacred mountain system.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":3}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:audience_fit:wudang-mountain-best-fit-travelers',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'audience_fit',
  'Wudang Mountain best-fit travelers',
  'Wudang Mountain is best for: Taoism, philosophy, and martial culture travelers; Guests seeking reflective mountain travel; Wellness-adjacent travelers who want real culture; Repeat China visitors looking beyond standard routes.',
  array['audience', 'conversion']::text[],
  '{"best_for":["Taoism, philosophy, and martial culture travelers","Guests seeking reflective mountain travel","Wellness-adjacent travelers who want real culture","Repeat China visitors looking beyond standard routes"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:route_seed:taoist-mountain-primer',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'route_seed',
  'Taoist Mountain Primer',
  'Taoist Mountain Primer (2-3 days): Temple sequence, mountain routes, Taoist interpretation, early morning light, and a short Taiji introduction.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":1,"duration":"2-3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:route_seed:practice-and-stillness',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'route_seed',
  'Practice and Stillness',
  'Practice and Stillness (4 days): Slow temple walking, private contextual practice, philosophy-led interpretation, and unhurried mountain time.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":2,"duration":"4 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:route_seed:wudang-and-beijing',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'route_seed',
  'Wudang and Beijing',
  'Wudang and Beijing (6-7 days): Contrast Beijing''s state ritual and axial order with Wudang''s mountain spirituality and internal cultivation.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":3,"duration":"6-7 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:traveler_faq:is-wudang-mainly-for-martial-arts-fans',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'traveler_faq',
  'Is Wudang mainly for martial arts fans?',
  'Question: Is Wudang mainly for martial arts fans?
Answer direction: No. Martial culture matters, but the deeper appeal is Taoist mountain culture, architecture, philosophy, and embodied practice.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:traveler_faq:how-should-wudang-be-paced',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'traveler_faq',
  'How should Wudang be paced?',
  'Question: How should Wudang be paced?
Answer direction: Slowly. The route should leave space for light, weather, walking, breathing, and interpretation rather than packing too many stops.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
)
on conflict (id) do update set
  destination_slug = excluded.destination_slug,
  destination_name = excluded.destination_name,
  language = excluded.language,
  content_type = excluded.content_type,
  title = excluded.title,
  body = excluded.body,
  tags = excluded.tags,
  metadata = excluded.metadata,
  source = excluded.source,
  source_url = excluded.source_url,
  source_confidence = excluded.source_confidence,
  content_version = excluded.content_version,
  updated_at = timezone('utc', now());
