insert into public.rag_documents (
  id,
  destination_slug,
  destination_name,
  language,
  content_type,
  title,
  body,
  tags,
  metadata,
  source,
  source_url,
  source_confidence,
  content_version
)
values
(
  'beijing:positioning_overview:beijing-positioning-overview',
  'beijing',
  'Beijing',
  'en',
  'positioning_overview',
  'Beijing positioning overview',
  'China''s capital is strongest when it is read as a city of order, ritual, power, and ordinary courtyard life.

Why visit: Beijing gives foreign travelers a clear way to understand how imperial authority, ceremonial space, socialist memory, and neighborhood texture coexist. The value is not only the Forbidden City or the Great Wall. It is the contrast between monumental axes and human-scale hutongs, between state ritual and small daily habits.

Avoid framing: Do not frame Beijing as a checklist of famous sights. The premium version is about reading power, space, ritual, and neighborhood life with context.',
  array['why_visit', 'positioning', 'avoid_generic']::text[],
  '{"best_for":["First-time visitors who want historical context","Architecture and urban planning travelers","Culture-led families or private small groups","Museum, history, and diplomacy-minded guests"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:sell_point:imperial-order-and-the-central-axis',
  'beijing',
  'Beijing',
  'en',
  'sell_point',
  'Imperial order and the Central Axis',
  'Beijing selling point: Imperial order and the Central Axis. Use palace space, gates, altars, and axial planning to explain how power was staged, not just where emperors lived.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:sell_point:hutongs-and-courtyard-life',
  'beijing',
  'Beijing',
  'en',
  'sell_point',
  'Hutongs and courtyard life',
  'Beijing selling point: Hutongs and courtyard life. Slow walks, local markets, and courtyard conversations make the capital feel lived-in rather than only monumental.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:sell_point:a-strong-first-china-orientation',
  'beijing',
  'Beijing',
  'en',
  'sell_point',
  'A strong first-China orientation',
  'Beijing selling point: A strong first-China orientation. Beijing works well as the first city for travelers who need historical grammar before moving into craft, tea, or regional culture.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":3}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:audience_fit:beijing-best-fit-travelers',
  'beijing',
  'Beijing',
  'en',
  'audience_fit',
  'Beijing best-fit travelers',
  'Beijing is best for: First-time visitors who want historical context; Architecture and urban planning travelers; Culture-led families or private small groups; Museum, history, and diplomacy-minded guests.',
  array['audience', 'conversion']::text[],
  '{"best_for":["First-time visitors who want historical context","Architecture and urban planning travelers","Culture-led families or private small groups","Museum, history, and diplomacy-minded guests"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:route_seed:capital-order',
  'beijing',
  'Beijing',
  'en',
  'route_seed',
  'Capital Order',
  'Capital Order (3 days): Central Axis, Forbidden City context, altar culture, hutong walks, and one carefully paced Great Wall day.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":1,"duration":"3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:route_seed:courtyard-beijing',
  'beijing',
  'Beijing',
  'en',
  'route_seed',
  'Courtyard Beijing',
  'Courtyard Beijing (4 days): Hutongs, courtyard meals, local markets, temple routes, and slower neighborhood interpretation.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":2,"duration":"4 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:route_seed:beijing-as-prologue',
  'beijing',
  'Beijing',
  'en',
  'route_seed',
  'Beijing as Prologue',
  'Beijing as Prologue (2-3 days): Use Beijing to establish China''s historical frame before continuing to Jingdezhen, Quanzhou, Wudang, or Chengdu.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":3,"duration":"2-3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:traveler_faq:why-should-a-culture-focused-traveler-start-in-beijing',
  'beijing',
  'Beijing',
  'en',
  'traveler_faq',
  'Why should a culture-focused traveler start in Beijing?',
  'Question: Why should a culture-focused traveler start in Beijing?
Answer direction: It gives the clearest opening frame for Chinese history, space, hierarchy, ritual, and urban continuity.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:traveler_faq:how-do-we-avoid-making-beijing-feel-generic',
  'beijing',
  'Beijing',
  'en',
  'traveler_faq',
  'How do we avoid making Beijing feel generic?',
  'Question: How do we avoid making Beijing feel generic?
Answer direction: Reduce checklist pressure and build the route around contrasts: axis and alley, palace and courtyard, ceremony and daily life.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:positioning_overview:chengdu-positioning-overview',
  'chengdu',
  'Chengdu',
  'en',
  'positioning_overview',
  'Chengdu positioning overview',
  'Chengdu is the easiest major Chinese city for foreigners to love through food, pandas, tea houses, and an unhurried social rhythm.

Why visit: Chengdu should lead with Sichuan food and pandas because those are the strongest emotional entry points for most foreign visitors. The deeper sell is that food, tea, parks, conversation, and neighborhood ease reveal a relaxed but culturally dense version of urban China.

Avoid framing: Do not reduce Chengdu to spicy food alone. Food and pandas should open the door, but the premium story is local ease, tea-house rhythm, and Sichuan social life.',
  array['why_visit', 'positioning', 'avoid_generic']::text[],
  '{"best_for":["Food-first travelers","Families and couples","Travelers who want China to feel relaxed, not overwhelming","Guests pairing pandas with Sichuan culture"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:sell_point:sichuan-food-as-culture',
  'chengdu',
  'Chengdu',
  'en',
  'sell_point',
  'Sichuan food as culture',
  'Chengdu selling point: Sichuan food as culture. Hotpot, snacks, market flavor, peppercorn aroma, and local dining habits turn meals into the main cultural route.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:sell_point:pandas-as-emotional-gateway',
  'chengdu',
  'Chengdu',
  'en',
  'sell_point',
  'Pandas as emotional gateway',
  'Chengdu selling point: Pandas as emotional gateway. Pandas create immediate desire, especially for families and first-time visitors, then the trip can deepen into local life.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:sell_point:tea-house-pace',
  'chengdu',
  'Chengdu',
  'en',
  'sell_point',
  'Tea-house pace',
  'Chengdu selling point: Tea-house pace. Parks, tea houses, mahjong, and long afternoons make Chengdu feel approachable, social, and human.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":3}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:audience_fit:chengdu-best-fit-travelers',
  'chengdu',
  'Chengdu',
  'en',
  'audience_fit',
  'Chengdu best-fit travelers',
  'Chengdu is best for: Food-first travelers; Families and couples; Travelers who want China to feel relaxed, not overwhelming; Guests pairing pandas with Sichuan culture.',
  array['audience', 'conversion']::text[],
  '{"best_for":["Food-first travelers","Families and couples","Travelers who want China to feel relaxed, not overwhelming","Guests pairing pandas with Sichuan culture"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:route_seed:food-and-panda-first',
  'chengdu',
  'Chengdu',
  'en',
  'route_seed',
  'Food and Panda First',
  'Food and Panda First (3 days): Panda base early morning, neighborhood snacks, hotpot, tea house, and a market-led flavor walk.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":1,"duration":"3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:route_seed:slow-chengdu',
  'chengdu',
  'Chengdu',
  'en',
  'route_seed',
  'Slow Chengdu',
  'Slow Chengdu (4 days): Parks, teahouses, old streets, Sichuan opera, food neighborhoods, and one gentle countryside or craft extension.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":2,"duration":"4 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:route_seed:chengdu-and-chongqing-contrast',
  'chengdu',
  'Chengdu',
  'en',
  'route_seed',
  'Chengdu and Chongqing Contrast',
  'Chengdu and Chongqing Contrast (5-6 days): Pair Chengdu''s softness and food culture with Chongqing''s 8D visual intensity and river-city drama.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":3,"duration":"5-6 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:traveler_faq:is-chengdu-only-about-pandas',
  'chengdu',
  'Chengdu',
  'en',
  'traveler_faq',
  'Is Chengdu only about pandas?',
  'Question: Is Chengdu only about pandas?
Answer direction: No. Pandas are the strongest hook, but the memorable trip comes from food, tea houses, parks, and local social rhythm.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chengdu:traveler_faq:who-is-chengdu-best-for',
  'chengdu',
  'Chengdu',
  'en',
  'traveler_faq',
  'Who is Chengdu best for?',
  'Question: Who is Chengdu best for?
Answer direction: Travelers who want culture through appetite, comfort, and daily life rather than only monuments.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:positioning_overview:chongqing-positioning-overview',
  'chongqing',
  'Chongqing',
  'en',
  'positioning_overview',
  'Chongqing positioning overview',
  'Chongqing is China''s most cinematic 8D mountain city: cyberpunk-feeling nights, impossible levels, hotpot heat, rivers, bridges, and vertical daily life.

Why visit: Chongqing should be sold as a sensory urban experience that feels unlike flat-grid cities. Foreign travelers remember the way trains, bridges, stairs, riverbanks, cliffside buildings, neon, fog, and hotpot combine into a city that feels almost fictional but is fully lived-in.

Avoid framing: Do not present Chongqing as just another food city or a list of viral photo spots. The sell is the lived 8D geography plus night movement, appetite, and river-city scale.',
  array['why_visit', 'positioning', 'avoid_generic']::text[],
  '{"best_for":["Visual travelers and photographers","Young premium travelers who want atmosphere","Food and nightlife-led guests","Visitors who want a city that feels different from Beijing or Shanghai"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:sell_point:cyberpunk-feeling-8d-geography',
  'chongqing',
  'Chongqing',
  'en',
  'sell_point',
  'Cyberpunk-feeling 8D geography',
  'Chongqing selling point: Cyberpunk-feeling 8D geography. Layered roads, monorails, cliffside buildings, river crossings, and sudden elevation changes create the city''s strongest visual identity.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:sell_point:night-city-and-river-drama',
  'chongqing',
  'Chongqing',
  'en',
  'sell_point',
  'Night city and river drama',
  'Chongqing selling point: Night city and river drama. Neon, humidity, bridges, ferries, and high viewpoints make Chongqing especially strong for evening routes and photography.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:sell_point:hotpot-and-mountain-city-appetite',
  'chongqing',
  'Chongqing',
  'en',
  'sell_point',
  'Hotpot and mountain-city appetite',
  'Chongqing selling point: Hotpot and mountain-city appetite. Food is not decoration here. Heat, noise, late meals, and communal dining match the city''s physical intensity.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":3}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:audience_fit:chongqing-best-fit-travelers',
  'chongqing',
  'Chongqing',
  'en',
  'audience_fit',
  'Chongqing best-fit travelers',
  'Chongqing is best for: Visual travelers and photographers; Young premium travelers who want atmosphere; Food and nightlife-led guests; Visitors who want a city that feels different from Beijing or Shanghai.',
  array['audience', 'conversion']::text[],
  '{"best_for":["Visual travelers and photographers","Young premium travelers who want atmosphere","Food and nightlife-led guests","Visitors who want a city that feels different from Beijing or Shanghai"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:route_seed:8d-city-immersion',
  'chongqing',
  'Chongqing',
  'en',
  'route_seed',
  '8D City Immersion',
  '8D City Immersion (2-3 days): Layered transit, old stairs, river crossings, high viewpoints, neon night walks, and one proper hotpot evening.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":1,"duration":"2-3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:route_seed:cyberpunk-chongqing',
  'chongqing',
  'Chongqing',
  'en',
  'route_seed',
  'Cyberpunk Chongqing',
  'Cyberpunk Chongqing (3 days): Focus on visual rhythm: monorail moments, bridges, elevated streets, fog, nightscape, and dense local neighborhoods.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":2,"duration":"3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:route_seed:sichuan-basin-pairing',
  'chongqing',
  'Chongqing',
  'en',
  'route_seed',
  'Sichuan Basin Pairing',
  'Sichuan Basin Pairing (5-6 days): Contrast Chengdu''s ease and pandas with Chongqing''s vertical drama, hotpot, and urban intensity.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":3,"duration":"5-6 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:traveler_faq:why-is-chongqing-called-an-8d-city',
  'chongqing',
  'Chongqing',
  'en',
  'traveler_faq',
  'Why is Chongqing called an 8D city?',
  'Question: Why is Chongqing called an 8D city?
Answer direction: Because roads, rails, buildings, riverbanks, and walkways stack across multiple levels, making navigation feel vertical and cinematic.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'chongqing:traveler_faq:is-chongqing-suitable-for-luxury-cultural-travel',
  'chongqing',
  'Chongqing',
  'en',
  'traveler_faq',
  'Is Chongqing suitable for luxury cultural travel?',
  'Question: Is Chongqing suitable for luxury cultural travel?
Answer direction: Yes, if the route is curated around atmosphere, viewpoints, local food, and urban interpretation rather than generic viral stops.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:positioning_overview:quanzhou-positioning-overview',
  'quanzhou',
  'Quanzhou',
  'en',
  'positioning_overview',
  'Quanzhou positioning overview',
  'Quanzhou is a world-class Maritime Silk Road port where UNESCO heritage, plural religions, Hokkien memory, food, and craft still overlap in the streets.

Why visit: Quanzhou is strongest for travelers who want China connected to the wider world. Its value is not beach tourism. It is the rare combination of Song-Yuan maritime trade, temples, mosques, ancestral memory, overseas Chinese ties, foodways, and living craft traditions.

Avoid framing: Do not sell Quanzhou as a generic coastal city. The premium story is port memory, religious plurality, Hokkien identity, food, and hand-made heritage.',
  array['why_visit', 'positioning', 'avoid_generic']::text[],
  '{"best_for":["Southeast Asian Hokkien and diaspora travelers","UNESCO and maritime history travelers","Religion, food, and old-city walkers","Travelers seeking depth beyond famous first-tier cities"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:sell_point:maritime-silk-road-and-unesco-heritage',
  'quanzhou',
  'Quanzhou',
  'en',
  'sell_point',
  'Maritime Silk Road and UNESCO heritage',
  'Quanzhou selling point: Maritime Silk Road and UNESCO heritage. Quanzhou explains China as a global port civilization, not an isolated inland empire.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:sell_point:plural-religions-and-coexistence',
  'quanzhou',
  'Quanzhou',
  'en',
  'sell_point',
  'Plural religions and coexistence',
  'Quanzhou selling point: Plural religions and coexistence. Mosques, temples, shrines, churches, and trade memory give the city unusual interpretive depth for foreign visitors.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:sell_point:hokkien-diaspora-and-living-food-culture',
  'quanzhou',
  'Quanzhou',
  'en',
  'sell_point',
  'Hokkien diaspora and living food culture',
  'Quanzhou selling point: Hokkien diaspora and living food culture. For Southeast Asian travelers especially, Quanzhou can feel like an origin story for family memory, language, worship, and flavor.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":3}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:audience_fit:quanzhou-best-fit-travelers',
  'quanzhou',
  'Quanzhou',
  'en',
  'audience_fit',
  'Quanzhou best-fit travelers',
  'Quanzhou is best for: Southeast Asian Hokkien and diaspora travelers; UNESCO and maritime history travelers; Religion, food, and old-city walkers; Travelers seeking depth beyond famous first-tier cities.',
  array['audience', 'conversion']::text[],
  '{"best_for":["Southeast Asian Hokkien and diaspora travelers","UNESCO and maritime history travelers","Religion, food, and old-city walkers","Travelers seeking depth beyond famous first-tier cities"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:route_seed:maritime-world-city',
  'quanzhou',
  'Quanzhou',
  'en',
  'route_seed',
  'Maritime World City',
  'Maritime World City (3 days): Old port memory, UNESCO components, religious sites, street food, and a slow old-city route.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":1,"duration":"3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:route_seed:hokkien-roots',
  'quanzhou',
  'Quanzhou',
  'en',
  'route_seed',
  'Hokkien Roots',
  'Hokkien Roots (4 days): Ancestral halls, temple culture, food memory, diaspora interpretation, and optional clan or village extensions.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":2,"duration":"4 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:route_seed:craft-and-ritual-quanzhou',
  'quanzhou',
  'Quanzhou',
  'en',
  'route_seed',
  'Craft and Ritual Quanzhou',
  'Craft and Ritual Quanzhou (5 days): Zanhua, Nanyin, incense, tea, ceramics, local markets, and religious landscapes shaped into an immersive route.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":3,"duration":"5 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:traveler_faq:which-foreign-markets-are-most-naturally-attracted-to-quanzhou',
  'quanzhou',
  'Quanzhou',
  'en',
  'traveler_faq',
  'Which foreign markets are most naturally attracted to Quanzhou?',
  'Question: Which foreign markets are most naturally attracted to Quanzhou?
Answer direction: Philippines, Malaysia, Singapore, Indonesia, and Thailand are especially strong because of Hokkien, diaspora, food, and temple connections.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'quanzhou:traveler_faq:what-makes-quanzhou-different-from-xiamen',
  'quanzhou',
  'Quanzhou',
  'en',
  'traveler_faq',
  'What makes Quanzhou different from Xiamen?',
  'Question: What makes Quanzhou different from Xiamen?
Answer direction: Xiamen is easier and more polished; Quanzhou is deeper for maritime heritage, religious plurality, old streets, and living traditions.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:positioning_overview:jingdezhen-positioning-overview',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'positioning_overview',
  'Jingdezhen positioning overview',
  'Jingdezhen is not only a porcelain museum city; it is a living craft ecosystem where clay, kiln, glaze, studio, and global design still meet.

Why visit: Jingdezhen gives foreign travelers a tactile way into Chinese culture. Instead of only viewing heritage, they can understand material, process, labor, failure, beauty, and global trade through porcelain. It is especially strong for design-minded and craft-minded guests.

Avoid framing: Do not frame Jingdezhen as a shopping stop. The premium value is the craft ecosystem: kilns, studios, makers, materials, and global porcelain history.',
  array['why_visit', 'positioning', 'avoid_generic']::text[],
  '{"best_for":["Design, craft, and architecture travelers","Museum and collector audiences","Artists, students, and creative professionals","Travelers who prefer process over sightseeing"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:sell_point:world-porcelain-capital',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'sell_point',
  'World porcelain capital',
  'Jingdezhen selling point: World porcelain capital. The city''s global significance is easy to explain: porcelain from here shaped taste, trade, collecting, and design across continents.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:sell_point:living-studios-and-kilns',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'sell_point',
  'Living studios and kilns',
  'Jingdezhen selling point: Living studios and kilns. The best route should include makers, workshops, firing culture, and contemporary craft, not only museums.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:sell_point:high-value-craft-experience',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'sell_point',
  'High-value craft experience',
  'Jingdezhen selling point: High-value craft experience. Jingdezhen is ideal for travelers who want to learn by seeing hands, tools, material choices, and process.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":3}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:audience_fit:jingdezhen-best-fit-travelers',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'audience_fit',
  'Jingdezhen best-fit travelers',
  'Jingdezhen is best for: Design, craft, and architecture travelers; Museum and collector audiences; Artists, students, and creative professionals; Travelers who prefer process over sightseeing.',
  array['audience', 'conversion']::text[],
  '{"best_for":["Design, craft, and architecture travelers","Museum and collector audiences","Artists, students, and creative professionals","Travelers who prefer process over sightseeing"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:route_seed:porcelain-deep-dive',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'route_seed',
  'Porcelain Deep Dive',
  'Porcelain Deep Dive (3 days): Historic kilns, museum context, studio visits, market texture, and one hands-on making or glazing session.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":1,"duration":"3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:route_seed:designer-jingdezhen',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'route_seed',
  'Designer Jingdezhen',
  'Designer Jingdezhen (4 days): Contemporary studios, independent makers, material research, old kiln districts, and curated collecting guidance.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":2,"duration":"4 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:route_seed:porcelain-and-capital-contrast',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'route_seed',
  'Porcelain and Capital Contrast',
  'Porcelain and Capital Contrast (6-7 days): Pair Beijing''s imperial order with Jingdezhen''s material culture to show power, taste, trade, and craft.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":3,"duration":"6-7 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:traveler_faq:why-would-a-foreign-traveler-go-to-jingdezhen',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'traveler_faq',
  'Why would a foreign traveler go to Jingdezhen?',
  'Question: Why would a foreign traveler go to Jingdezhen?
Answer direction: Because it turns Chinese culture into something physical and understandable through clay, firing, craft, and global porcelain history.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingdezhen:traveler_faq:is-jingdezhen-only-for-collectors',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'traveler_faq',
  'Is Jingdezhen only for collectors?',
  'Question: Is Jingdezhen only for collectors?
Answer direction: No. It is also strong for designers, families, students, artists, and travelers who want hands-on cultural experience.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:positioning_overview:jingmai-mountain-positioning-overview',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'positioning_overview',
  'Jingmai Mountain positioning overview',
  'Jingmai is a slow tea mountain world where ancient tea forests, villages, ecology, and ritual create a quieter, more contemplative China route.

Why visit: Jingmai should be developed as a high-aesthetic slow travel destination, not a conventional attraction cluster. Its power comes from tea landscapes, mountain air, village continuity, ethnic culture, ecology, and the emotional shift that happens when the trip slows down.

Avoid framing: Do not sell Jingmai as a fast sightseeing stop. The value depends on slowness, weather, tea ritual, mountain texture, and local interpretation.',
  array['why_visit', 'positioning', 'avoid_generic']::text[],
  '{"best_for":["Tea travelers and nature-focused guests","Slow travel and retreat-style visitors","Photographers and high-aesthetic travelers","Repeat China visitors seeking less obvious routes"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:sell_point:ancient-tea-forest-landscape',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'sell_point',
  'Ancient tea forest landscape',
  'Jingmai Mountain selling point: Ancient tea forest landscape. Tea is not just a drink here. It is a landscape, livelihood, ritual, ecology, and way to read time.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:sell_point:slow-mountain-travel',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'sell_point',
  'Slow mountain travel',
  'Jingmai Mountain selling point: Slow mountain travel. The appeal is pace reduction: mist, mornings, tea, walking, village stays, and distance from mass tourism.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:sell_point:a-strong-premium-retreat-angle',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'sell_point',
  'A strong premium retreat angle',
  'Jingmai Mountain selling point: A strong premium retreat angle. Jingmai fits travelers seeking silence, beauty, wellness-adjacent culture, and reflective travel without making it generic wellness tourism.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":3}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:audience_fit:jingmai-mountain-best-fit-travelers',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'audience_fit',
  'Jingmai Mountain best-fit travelers',
  'Jingmai Mountain is best for: Tea travelers and nature-focused guests; Slow travel and retreat-style visitors; Photographers and high-aesthetic travelers; Repeat China visitors seeking less obvious routes.',
  array['audience', 'conversion']::text[],
  '{"best_for":["Tea travelers and nature-focused guests","Slow travel and retreat-style visitors","Photographers and high-aesthetic travelers","Repeat China visitors seeking less obvious routes"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:route_seed:tea-forest-stay',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'route_seed',
  'Tea Forest Stay',
  'Tea Forest Stay (3 days): Village base, tea forest walks, tea tasting, mountain mornings, and conversations around ecology and craft.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":1,"duration":"3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:route_seed:slow-yunnan-tea-route',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'route_seed',
  'Slow Yunnan Tea Route',
  'Slow Yunnan Tea Route (5 days): Jingmai with nearby tea landscapes, village rhythm, light hiking, and careful lodge pacing.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":2,"duration":"5 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:route_seed:tea-and-craft-china',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'route_seed',
  'Tea and Craft China',
  'Tea and Craft China (7 days): Pair Jingmai''s tea ecology with Jingdezhen''s porcelain process for a material culture route.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":3,"duration":"7 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:traveler_faq:why-is-jingmai-worth-including',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'traveler_faq',
  'Why is Jingmai worth including?',
  'Question: Why is Jingmai worth including?
Answer direction: It adds quiet, ecology, tea culture, and emotional contrast to an itinerary that might otherwise be too city-heavy.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'jingmai-mountain:traveler_faq:who-should-not-choose-jingmai',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'traveler_faq',
  'Who should not choose Jingmai?',
  'Question: Who should not choose Jingmai?
Answer direction: Travelers who want fast logistics, dense nightlife, or a simple checklist route may find it too slow.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:positioning_overview:wudang-mountain-positioning-overview',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'positioning_overview',
  'Wudang Mountain positioning overview',
  'Wudang Mountain is a Taoist sacred landscape where architecture, mountain paths, Taiji, breath, and internal practice give the trip spiritual weight.

Why visit: Wudang should be positioned around Taoist culture and Taiji, not just mountain scenery. For foreign travelers, it offers an unusually coherent combination of sacred architecture, philosophy, martial tradition, body practice, early light, and reflective travel.

Avoid framing: Do not sell Wudang as generic scenery or kung fu performance. The premium route needs Taoist context, Taiji literacy, mountain pacing, and quiet.',
  array['why_visit', 'positioning', 'avoid_generic']::text[],
  '{"best_for":["Taoism, philosophy, and martial culture travelers","Guests seeking reflective mountain travel","Wellness-adjacent travelers who want real culture","Repeat China visitors looking beyond standard routes"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:sell_point:taoist-sacred-mountain',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'sell_point',
  'Taoist sacred mountain',
  'Wudang Mountain selling point: Taoist sacred mountain. Temples, palaces, paths, and mountain orientation create a strong philosophical landscape, not just a scenic one.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:sell_point:taiji-and-internal-practice',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'sell_point',
  'Taiji and internal practice',
  'Wudang Mountain selling point: Taiji and internal practice. Short, well-contextualized practice sessions can make the destination memorable without pretending to be a training camp.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:sell_point:architecture-and-atmosphere',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'sell_point',
  'Architecture and atmosphere',
  'Wudang Mountain selling point: Architecture and atmosphere. Wudang''s appeal is strongest in early light, temple routes, clouds, silence, and the feeling of movement through a sacred mountain system.',
  array['sell_point', 'city_identity']::text[],
  '{"sort_order":3}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:audience_fit:wudang-mountain-best-fit-travelers',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'audience_fit',
  'Wudang Mountain best-fit travelers',
  'Wudang Mountain is best for: Taoism, philosophy, and martial culture travelers; Guests seeking reflective mountain travel; Wellness-adjacent travelers who want real culture; Repeat China visitors looking beyond standard routes.',
  array['audience', 'conversion']::text[],
  '{"best_for":["Taoism, philosophy, and martial culture travelers","Guests seeking reflective mountain travel","Wellness-adjacent travelers who want real culture","Repeat China visitors looking beyond standard routes"]}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:route_seed:taoist-mountain-primer',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'route_seed',
  'Taoist Mountain Primer',
  'Taoist Mountain Primer (2-3 days): Temple sequence, mountain routes, Taoist interpretation, early morning light, and a short Taiji introduction.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":1,"duration":"2-3 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:route_seed:practice-and-stillness',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'route_seed',
  'Practice and Stillness',
  'Practice and Stillness (4 days): Slow temple walking, private contextual practice, philosophy-led interpretation, and unhurried mountain time.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":2,"duration":"4 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:route_seed:wudang-and-beijing',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'route_seed',
  'Wudang and Beijing',
  'Wudang and Beijing (6-7 days): Contrast Beijing''s state ritual and axial order with Wudang''s mountain spirituality and internal cultivation.',
  array['route_seed', 'itinerary']::text[],
  '{"sort_order":3,"duration":"6-7 days"}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:traveler_faq:is-wudang-mainly-for-martial-arts-fans',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'traveler_faq',
  'Is Wudang mainly for martial arts fans?',
  'Question: Is Wudang mainly for martial arts fans?
Answer direction: No. Martial culture matters, but the deeper appeal is Taoist mountain culture, architecture, philosophy, and embodied practice.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":1}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'wudang-mountain:traveler_faq:how-should-wudang-be-paced',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'traveler_faq',
  'How should Wudang be paced?',
  'Question: How should Wudang be paced?
Answer direction: Slowly. The route should leave space for light, weather, walking, breathing, and interpretation rather than packing too many stops.',
  array['faq', 'traveler_question']::text[],
  '{"sort_order":2}'::jsonb,
  'a-deeper-china-redesign/lib/destination-positioning.ts',
  null,
  'curated',
  'v1-static-positioning'
),
(
  'beijing:experience:read-the-central-axis-as-a-ritual-machine',
  'beijing',
  'Beijing',
  'en',
  'experience',
  'Read the Central Axis as a ritual machine',
  'For a culture-led Beijing route, the Central Axis should be explained as a designed sequence of gates, thresholds, courts, altars, and sightlines. The visitor is not only seeing famous buildings; they are learning how imperial China made power visible through symmetry, distance, approach, and ceremony.',
  array['beijing', 'central_axis', 'ritual_space', 'architecture']::text[],
  '{"why_it_matters":"Turns familiar monuments into an interpretive story about power and spatial order.","detail_type":"experience_cluster"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'beijing:experience:hutong-mornings-before-the-tourist-day-starts',
  'beijing',
  'Beijing',
  'en',
  'experience',
  'Hutong mornings before the tourist day starts',
  'The strongest hutong experience is early and slow: breakfast stalls, bicycle movement, school runs, market sounds, courtyard doorways, and small neighborhood rituals. This makes Beijing feel lived-in rather than reduced to palace history.',
  array['beijing', 'hutong', 'daily_life', 'slow_walk']::text[],
  '{"best_for":["return visitors","photographers","families"],"detail_type":"experience_cluster"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'beijing:food:beijing-food-as-northern-urban-memory',
  'beijing',
  'Beijing',
  'en',
  'food',
  'Beijing food as northern urban memory',
  'Instead of presenting Beijing food as a restaurant list, connect noodles, dumplings, hotpot, roast duck, breakfast breads, sesame paste, and seasonal snacks to migration, winter climate, imperial service economies, and neighborhood routines.',
  array['beijing', 'food', 'context', 'northern_china']::text[],
  '{"concierge_use":"Use when a traveler asks what to eat beyond Peking duck.","detail_type":"food_context"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'beijing:route_seed:do-not-overload-beijing-day-one',
  'beijing',
  'Beijing',
  'en',
  'route_seed',
  'Do not overload Beijing day one',
  'For foreign travelers arriving long-haul, Beijing works better with one anchoring site, one neighborhood walk, and one atmospheric meal. Saving the Forbidden City or Great Wall for a clearer morning often produces a better premium experience than forcing a checklist immediately.',
  array['beijing', 'arrival_day', 'pacing', 'route_design']::text[],
  '{"avoid":"Jet-lagged monument stacking.","detail_type":"route_design_note"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'beijing:market_profile:beijing-for-design-and-urban-planning-travelers',
  'beijing',
  'Beijing',
  'en',
  'market_profile',
  'Beijing for design and urban planning travelers',
  'Design-minded travelers can read Beijing through axes, courtyard typologies, socialist boulevards, ring roads, hutong preservation, adaptive reuse, and the tension between planned order and everyday improvisation.',
  array['beijing', 'design_travel', 'urban_planning', 'architecture']::text[],
  '{"market_fit":["architects","design schools","museum patrons"],"detail_type":"audience_angle"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'beijing:source_note:why-book-a-beijing-expert',
  'beijing',
  'Beijing',
  'en',
  'source_note',
  'Why book a Beijing expert',
  'Beijing is easy to visit but hard to read. A good expert adds value by explaining hierarchy, ritual, symbolism, neighborhood history, and pacing, so the traveler does not leave with only photos of large buildings.',
  array['beijing', 'expert', 'conversion', 'interpretation']::text[],
  '{"cta":"Offer a private route reading rather than generic guiding.","detail_type":"conversion_hook"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'chengdu:experience:pandas-as-the-soft-entry-into-sichuan',
  'chengdu',
  'Chengdu',
  'en',
  'experience',
  'Pandas as the soft entry into Sichuan',
  'For most foreign travelers, pandas create immediate emotional desire. The route should use that attention as an opening, then move into Sichuan food, tea houses, parks, opera, and neighborhood life so Chengdu becomes more than a single animal encounter.',
  array['chengdu', 'pandas', 'family_travel', 'emotional_hook']::text[],
  '{"best_for":["families","couples","first-time China visitors"],"detail_type":"experience_cluster"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'chengdu:food:sichuan-food-is-a-complete-travel-language',
  'chengdu',
  'Chengdu',
  'en',
  'food',
  'Sichuan food is a complete travel language',
  'Chengdu food should be explained through aroma, mouthfeel, peppercorn numbness, shared tables, late meals, snacks, markets, and the social confidence of local diners. The point is not only spice; it is how flavor organizes the day.',
  array['chengdu', 'sichuan_food', 'hotpot', 'street_food']::text[],
  '{"concierge_use":"Use when travelers ask whether Chengdu is too spicy.","detail_type":"food_context"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'chengdu:experience:tea-houses-as-chengdu-s-social-engine',
  'chengdu',
  'Chengdu',
  'en',
  'experience',
  'Tea houses as Chengdu''s social engine',
  'A Chengdu tea house is not filler time. It shows the city''s pace: sitting, talking, watching, playing mahjong, listening, and letting the afternoon stretch. For foreigners, it is one of the easiest ways to feel local life without heavy explanation.',
  array['chengdu', 'tea_house', 'slow_travel', 'daily_life']::text[],
  '{"why_it_matters":"Converts comfort into cultural depth.","detail_type":"experience_cluster"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'chengdu:route_seed:build-chengdu-around-appetite-and-rest',
  'chengdu',
  'Chengdu',
  'en',
  'route_seed',
  'Build Chengdu around appetite and rest',
  'Chengdu routes should leave enough space between meals. A premium route works better with fewer sites, stronger food choices, a tea-house pause, and one atmospheric evening than with a packed checklist.',
  array['chengdu', 'pacing', 'food_route', 'route_design']::text[],
  '{"avoid":"Over-scheduling before a serious dinner.","detail_type":"route_design_note"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'chengdu:market_profile:chengdu-for-travelers-nervous-about-china',
  'chengdu',
  'Chengdu',
  'en',
  'market_profile',
  'Chengdu for travelers nervous about China',
  'Chengdu can make China feel approachable because the emotional hooks are clear: pandas, food, parks, tea, warmth, and a slower street rhythm. It is useful for guests who want culture without feeling constantly overwhelmed.',
  array['chengdu', 'first_time_china', 'comfort', 'soft_landing']::text[],
  '{"market_fit":["families","older couples","comfort-seeking premium guests"],"detail_type":"audience_angle"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'chengdu:source_note:why-book-a-chengdu-food-expert',
  'chengdu',
  'Chengdu',
  'en',
  'source_note',
  'Why book a Chengdu food expert',
  'A food expert prevents Chengdu from becoming random spicy meals. The value is ordering well, controlling heat level, explaining ingredients, choosing the right neighborhood, and connecting each meal to Sichuan social life.',
  array['chengdu', 'expert', 'food_expert', 'conversion']::text[],
  '{"cta":"Offer a curated flavor walk or private hotpot ordering session.","detail_type":"conversion_hook"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'chongqing:experience:8d-navigation-as-the-attraction',
  'chongqing',
  'Chongqing',
  'en',
  'experience',
  '8D navigation as the attraction',
  'In Chongqing, movement itself is the experience. Elevators, stairs, ramps, monorails, bridges, tunnels, and layered roads make the city feel like a vertical puzzle. A good route should let travelers feel disoriented in a controlled and pleasurable way.',
  array['chongqing', '8d_city', 'urban_experience', 'navigation']::text[],
  '{"why_it_matters":"Makes the city memorable beyond individual photo spots.","detail_type":"experience_cluster"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'chongqing:experience:cyberpunk-feeling-chongqing-after-dark',
  'chongqing',
  'Chongqing',
  'en',
  'experience',
  'Cyberpunk-feeling Chongqing after dark',
  'Chongqing''s strongest visual hours are often evening and night, when neon, fog, river reflections, bridges, hillside towers, and moving trains create a cinematic atmosphere. The route should prioritize transitions, viewpoints, and walking sequences rather than one static overlook.',
  array['chongqing', 'cyberpunk', 'night', 'photography']::text[],
  '{"best_for":["photographers","younger premium travelers","visual storytellers"],"detail_type":"photo_route"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'chongqing:food:hotpot-as-mountain-city-temperament',
  'chongqing',
  'Chongqing',
  'en',
  'food',
  'Hotpot as mountain-city temperament',
  'Chongqing hotpot should be presented as part of the city''s intensity: heat, oil, steam, noise, late hours, shared risk, and appetite. It matches the geography rather than sitting apart from it.',
  array['chongqing', 'hotpot', 'food', 'nightlife']::text[],
  '{"concierge_use":"Use when comparing Chengdu and Chongqing food culture.","detail_type":"food_context"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'chongqing:route_seed:chongqing-needs-night-routing',
  'chongqing',
  'Chongqing',
  'en',
  'route_seed',
  'Chongqing needs night routing',
  'A Chongqing itinerary that ends too early misses the city''s strongest identity. At least one evening should be designed around river movement, height changes, lit bridges, hotpot, and a final viewpoint or walk.',
  array['chongqing', 'night_route', 'route_design', 'river_city']::text[],
  '{"avoid":"Daytime-only sightseeing.","detail_type":"route_design_note"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'chongqing:market_profile:chongqing-for-travelers-who-think-they-have-seen-china',
  'chongqing',
  'Chongqing',
  'en',
  'market_profile',
  'Chongqing for travelers who think they have seen China',
  'Chongqing works well for repeat visitors because it breaks expectations of what a Chinese city feels like. It is dense, vertical, humid, loud, cinematic, and emotionally different from capital, coastal, or garden-city narratives.',
  array['chongqing', 'repeat_china', 'visual_travel', 'city_contrast']::text[],
  '{"market_fit":["repeat visitors","Asia-savvy travelers","urban explorers"],"detail_type":"audience_angle"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'chongqing:source_note:why-book-a-chongqing-route-designer',
  'chongqing',
  'Chongqing',
  'en',
  'source_note',
  'Why book a Chongqing route designer',
  'Chongqing is easy to visit badly because navigation is confusing and viral stops can waste time. A route designer adds value by sequencing levels, transit, viewpoints, food, and night atmosphere into a coherent 8D experience.',
  array['chongqing', 'expert', 'route_design', 'conversion']::text[],
  '{"cta":"Offer a private 8D city walk and night route.","detail_type":"conversion_hook"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'quanzhou:experience:quanzhou-as-china-s-outward-facing-port-memory',
  'quanzhou',
  'Quanzhou',
  'en',
  'experience',
  'Quanzhou as China''s outward-facing port memory',
  'Quanzhou should be explained as a place where China met the wider world through trade, religion, migration, language, food, and craft. This is the opposite of a closed imperial narrative and makes the city especially legible for foreign visitors.',
  array['quanzhou', 'maritime_silk_road', 'world_heritage', 'port_city']::text[],
  '{"why_it_matters":"Differentiates Quanzhou from generic coastal tourism.","detail_type":"experience_cluster"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'quanzhou:market_profile:quanzhou-for-southeast-asian-hokkien-travelers',
  'quanzhou',
  'Quanzhou',
  'en',
  'market_profile',
  'Quanzhou for Southeast Asian Hokkien travelers',
  'For travelers from the Philippines, Malaysia, Singapore, Indonesia, and Thailand, Quanzhou can connect family memory, temple practice, dialect, food, surnames, and ancestral geography. The emotional sell is origin, not only heritage.',
  array['quanzhou', 'hokkien', 'diaspora', 'southeast_asia']::text[],
  '{"market_fit":["Philippines","Malaysia","Singapore","Indonesia","Thailand"],"detail_type":"audience_angle"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'quanzhou:experience:plural-religion-as-a-walking-route',
  'quanzhou',
  'Quanzhou',
  'en',
  'experience',
  'Plural religion as a walking route',
  'Quanzhou''s religious landscape can be shaped as a walking story: temples, mosques, shrines, churches, ancestor halls, maritime gods, traders, and families all appear in a compact urban fabric. The point is coexistence through daily life, not only monuments.',
  array['quanzhou', 'religion', 'old_city', 'walking_route']::text[],
  '{"best_for":["religion scholars","UNESCO travelers","Southeast Asian diaspora guests"],"detail_type":"experience_cluster"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'quanzhou:food:quanzhou-food-as-diaspora-memory',
  'quanzhou',
  'Quanzhou',
  'en',
  'food',
  'Quanzhou food as diaspora memory',
  'Food in Quanzhou should be connected to Minnan taste, port life, family kitchens, temple neighborhoods, snacks, seafood, noodle textures, and Southeast Asian echoes. For many visitors, flavor may feel like recognition rather than novelty.',
  array['quanzhou', 'food', 'minnan', 'diaspora']::text[],
  '{"concierge_use":"Use for Hokkien and Southeast Asian market personalization.","detail_type":"food_context"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'quanzhou:experience:zanhua-incense-tea-porcelain-and-nanyin-as-living-culture',
  'quanzhou',
  'Quanzhou',
  'en',
  'experience',
  'Zanhua, incense, tea, porcelain, and Nanyin as living culture',
  'Quanzhou''s craft and performance appeal should be treated as living systems: zanhua photography, incense making, Anxi tea, Dehua white porcelain, and Nanyin can turn heritage into touch, sound, scent, and embodied memory.',
  array['quanzhou', 'zanhua', 'incense', 'tea', 'nanyin', 'craft']::text[],
  '{"route_use":"Good for 4-5 day routes that move beyond old-city walking.","detail_type":"craft_context"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'quanzhou:source_note:why-book-a-quanzhou-cultural-interpreter',
  'quanzhou',
  'Quanzhou',
  'en',
  'source_note',
  'Why book a Quanzhou cultural interpreter',
  'Quanzhou contains layers that many visitors will miss alone: port history, clan memory, religious plurality, Minnan language, diaspora emotion, and craft meanings. The expert''s value is connecting fragments into a personal story.',
  array['quanzhou', 'expert', 'conversion', 'cultural_interpreter']::text[],
  '{"cta":"Offer a diaspora roots or Maritime Silk Road interpretation session.","detail_type":"conversion_hook"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'jingdezhen:experience:porcelain-as-a-world-system-story',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'experience',
  'Porcelain as a world-system story',
  'Jingdezhen is powerful because porcelain links local clay and kilns to global trade, royal collections, taste, imitation, technology, and design history. It lets foreign travelers understand China through objects that changed the world.',
  array['jingdezhen', 'porcelain', 'global_trade', 'design_history']::text[],
  '{"why_it_matters":"Connects craft to global cultural history.","detail_type":"experience_cluster"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'jingdezhen:experience:studio-visits-over-shopping-stops',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'experience',
  'Studio visits over shopping stops',
  'The premium Jingdezhen experience should prioritize studios, makers, materials, tools, firing, glazing, and failures. Shopping can happen, but it should follow understanding, not replace it.',
  array['jingdezhen', 'studio_visit', 'craft', 'maker_culture']::text[],
  '{"avoid":"Turning the city into a ceramics mall.","detail_type":"experience_cluster"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'jingdezhen:experience:hands-on-clay-work-needs-context',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'experience',
  'Hands-on clay work needs context',
  'A short making or glazing session is most valuable when framed by clay sourcing, wheel skill, kiln risk, glaze chemistry, and the difference between tourist activity and serious craft labor.',
  array['jingdezhen', 'hands_on', 'clay', 'glaze', 'craft_learning']::text[],
  '{"best_for":["families","designers","students","creative professionals"],"detail_type":"hands_on_experience"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'jingdezhen:market_profile:jingdezhen-for-design-schools-and-collectors',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'market_profile',
  'Jingdezhen for design schools and collectors',
  'Jingdezhen can support high-value groups because it offers museums, old kiln districts, working studios, contemporary makers, collecting conversations, and a clear bridge between historical craft and current design practice.',
  array['jingdezhen', 'design_school', 'collectors', 'creative_travel']::text[],
  '{"market_fit":["design schools","museum patrons","ceramics collectors"],"detail_type":"audience_angle"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'jingdezhen:route_seed:pair-jingdezhen-with-beijing-or-jingmai',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'route_seed',
  'Pair Jingdezhen with Beijing or Jingmai',
  'Jingdezhen pairs well with Beijing for power and taste, or with Jingmai for tea and porcelain as a material culture journey. These pairings help foreign travelers understand Chinese culture through use, ritual, and objects.',
  array['jingdezhen', 'route_pairing', 'beijing', 'jingmai', 'material_culture']::text[],
  '{"route_use":"Useful for 6-7 day premium routes.","detail_type":"route_design_note"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'jingdezhen:source_note:why-book-a-jingdezhen-maker-connection',
  'jingdezhen',
  'Jingdezhen',
  'en',
  'source_note',
  'Why book a Jingdezhen maker connection',
  'Jingdezhen''s best experiences are not always visible from public listings. A local maker connection can open studios, explain quality, avoid tourist traps, and help visitors understand what they are seeing or buying.',
  array['jingdezhen', 'expert', 'maker', 'conversion']::text[],
  '{"cta":"Offer a private studio-and-kiln route.","detail_type":"conversion_hook"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'jingmai-mountain:experience:ancient-tea-forest-as-living-landscape',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'experience',
  'Ancient tea forest as living landscape',
  'Jingmai should be understood as tea, forest, village, ecology, and memory woven together. The strongest experience is not a quick tasting but walking through a landscape where tea trees, households, rituals, and seasons form a living system.',
  array['jingmai', 'tea_forest', 'ecology', 'slow_travel']::text[],
  '{"why_it_matters":"Frames tea as landscape rather than beverage.","detail_type":"experience_cluster"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'jingmai-mountain:route_seed:jingmai-requires-slower-logistics',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'route_seed',
  'Jingmai requires slower logistics',
  'Jingmai is not suited to rushed itineraries. The route needs buffer time for mountain roads, weather, village pacing, tea sessions, and quiet mornings. The premium value appears only when the schedule stops fighting the place.',
  array['jingmai', 'logistics', 'slow_travel', 'pacing']::text[],
  '{"avoid":"Treating Jingmai as a one-night checklist stop.","detail_type":"route_design_note"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'jingmai-mountain:experience:tea-tasting-as-conversation-not-performance',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'experience',
  'Tea tasting as conversation, not performance',
  'A strong Jingmai tea session should connect leaf, age, forest, family practice, water, storage, taste, and hospitality. Foreign travelers need patient interpretation so tasting becomes cultural understanding rather than a confusing sequence of cups.',
  array['jingmai', 'tea', 'tasting', 'hospitality']::text[],
  '{"concierge_use":"Use when guests ask what they actually do in Jingmai.","detail_type":"tea_context"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'jingmai-mountain:market_profile:jingmai-for-high-aesthetic-retreat-travelers',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'market_profile',
  'Jingmai for high-aesthetic retreat travelers',
  'Jingmai fits travelers who want mist, texture, quiet, village time, tea, and a reflective break from urban China. It should not be sold as generic wellness; its retreat quality comes from real landscape and tea culture.',
  array['jingmai', 'retreat', 'wellness_adjacent', 'aesthetic_travel']::text[],
  '{"market_fit":["slow travelers","photographers","tea travelers","repeat China visitors"],"detail_type":"audience_angle"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'jingmai-mountain:route_seed:jingmai-and-jingdezhen-as-tea-and-porcelain-journey',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'route_seed',
  'Jingmai and Jingdezhen as tea-and-porcelain journey',
  'Pairing Jingmai with Jingdezhen creates a refined material culture route: tea forests, cups, clay, glaze, ritual, and the objects used to host people. It is a strong alternative to conventional city sightseeing.',
  array['jingmai', 'jingdezhen', 'tea', 'porcelain', 'material_culture']::text[],
  '{"duration":"7 days","detail_type":"route_pairing"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'jingmai-mountain:source_note:why-book-a-jingmai-tea-host',
  'jingmai_mountain',
  'Jingmai Mountain',
  'en',
  'source_note',
  'Why book a Jingmai tea host',
  'Without a host, Jingmai can feel beautiful but opaque. A good tea host explains village etiquette, tea choices, forest context, tasting language, and pacing, making the slow journey feel intentional.',
  array['jingmai', 'expert', 'tea_host', 'conversion']::text[],
  '{"cta":"Offer hosted tea forest days rather than generic sightseeing.","detail_type":"conversion_hook"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'wudang-mountain:experience:taoist-mountain-as-spatial-philosophy',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'experience',
  'Taoist mountain as spatial philosophy',
  'Wudang''s temples, paths, peaks, gates, courtyards, clouds, and ascent should be read as a philosophical landscape. The experience is strongest when architecture and movement are connected to Taoist ideas of balance, stillness, and cultivation.',
  array['wudang', 'taoism', 'sacred_mountain', 'architecture']::text[],
  '{"why_it_matters":"Prevents Wudang from becoming generic mountain scenery.","detail_type":"experience_cluster"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'wudang-mountain:experience:taiji-introduction-for-travelers-not-training-camp',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'experience',
  'Taiji introduction for travelers, not training camp',
  'A short Taiji session works best as embodied interpretation: posture, breath, weight shift, attention, and the idea of internal practice. Most visitors need a meaningful introduction, not an unrealistic martial arts promise.',
  array['wudang', 'taiji', 'body_practice', 'taoist_culture']::text[],
  '{"best_for":["wellness-adjacent travelers","philosophy travelers","families"],"detail_type":"hands_on_experience"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'wudang-mountain:route_seed:wudang-should-start-early',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'route_seed',
  'Wudang should start early',
  'Early light, quieter paths, thinner crowds, mountain air, and temple atmosphere are central to Wudang. A route that begins late loses much of the sacred-mountain feeling.',
  array['wudang', 'early_morning', 'pacing', 'mountain_route']::text[],
  '{"avoid":"Late-start checklist touring.","detail_type":"route_design_note"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'wudang-mountain:market_profile:wudang-for-philosophy-and-practice-travelers',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'market_profile',
  'Wudang for philosophy and practice travelers',
  'Wudang is especially strong for visitors who want culture through body and mind: Taoism, Taiji, breath, mountain walking, architecture, and reflective space. It is not only for martial arts fans.',
  array['wudang', 'philosophy', 'practice', 'reflective_travel']::text[],
  '{"market_fit":["Taoism learners","martial culture travelers","wellness-adjacent guests"],"detail_type":"audience_angle"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'wudang-mountain:route_seed:wudang-and-beijing-as-ritual-contrast',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'route_seed',
  'Wudang and Beijing as ritual contrast',
  'Beijing and Wudang make a strong contrast: state ritual and imperial order in the capital, then mountain spirituality and internal cultivation in Wudang. This pairing gives travelers two different models of Chinese order.',
  array['wudang', 'beijing', 'route_pairing', 'ritual_contrast']::text[],
  '{"duration":"6-7 days","detail_type":"route_pairing"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
),
(
  'wudang-mountain:source_note:why-book-a-wudang-practice-interpreter',
  'wudang_mountain',
  'Wudang Mountain',
  'en',
  'source_note',
  'Why book a Wudang practice interpreter',
  'A Wudang interpreter adds value by connecting temples, stories, Taoist ideas, Taiji movement, and route pacing. Without that context, visitors may see scenery and performances but miss the internal logic of the place.',
  array['wudang', 'expert', 'taiji', 'conversion']::text[],
  '{"cta":"Offer a Taoist mountain and Taiji primer.","detail_type":"conversion_hook"}'::jsonb,
  'a-deeper-china-redesign/content/rag/destination-knowledge-details.json',
  null,
  'curated',
  'v1-curated-detail-cards'
)
on conflict (id) do update set
  destination_slug = excluded.destination_slug,
  destination_name = excluded.destination_name,
  language = excluded.language,
  content_type = excluded.content_type,
  title = excluded.title,
  body = excluded.body,
  tags = excluded.tags,
  metadata = excluded.metadata,
  source = excluded.source,
  source_url = excluded.source_url,
  source_confidence = excluded.source_confidence,
  content_version = excluded.content_version,
  updated_at = timezone('utc', now());
